apiVersion: v1
kind: PersistentVolume
metadata:
    name: aws-ebs
    labels:
        app: green
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: awsebsvol