apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: aws-vol
    labels:
        app: green
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 4.5Gi
    storageClassName: awsebsvol
