apiVersion: apps/v1
kind: Deployment
metadata:
      name: blue
      labels:
        app: blue
spec:
      replicas: 1
      selector:
        matchLabels:
          app: blue
      template:
        metadata:
          labels:
            app: blue
        spec:
          containers:
          - name: blue
            image: nakotisanthosh/udacitybluecap
            volumeMounts:
              - mountPath: /mnt/test
                name: deployment-volume
            ports:
              - name: http-server
                containerPort: 80
          volumes:
            - name: deployment-volume
              emptyDir: {}
